feat: create initial structure for staticpub.distributed.press
hyphacoop/staticpub.distributed.press pull request #1
Opened 2024-11-21 07:34 UTC by akhileshthite

2024-11-27 20:54 UTC, RangerMauve requested changes

2024-11-27 20:54 UTC, RangerMauve commented on README.md
> +To replace all instances of `staticpub.mauve.moe` with `yourdomain.com`, `mauve` with `username`, and `"Mauve"` with `"Your Name"`, you can use the following sed commands:
Change this from `staticpub.mauve.moe` to `staticpub.distributed.press`. Maybe also change all instances of `Mauve` to `dp`?

2024-11-27 20:54 UTC, RangerMauve commented on README.md
> +Make sure to update the `publicKeyPem` field in the following files with your actual public key from the `.dprc` configuration file:
Link to the docs page for setting up the CLI

2024-11-27 22:14 UTC, RangerMauve commented on index.html
> +  </nav>
```suggestion
  </nav>
  <footer>
  <p style="font-family: Source Sans Pro; font-size: 0.8em;">
    <a href="//distributed.press">Powered By Distributed Press</a>
  </p>
  </footer>
```

2024-11-28 17:51 UTC, RangerMauve approved these changes
I set up the DNS, see if it works after a publish.

2024-11-28 18:08 UTC, akhileshthite commented
> I set up the DNS, see if it works after a publish.

Same issue; ipns and hyper are working but not http
![Screenshot 2024-11-28 at 10 06 30 AM](https://github.com/user-attachments/assets/00f30d43-1b8a-47bc-935c-b62e98f56534)

2024-12-02 16:20 UTC, RangerMauve commented
HTTPS works. Mind updating the "powered by distributed press" snippet then it should be good to merge.

2024-12-02 20:32 UTC, akhileshthite commented
> HTTPS works. Mind updating the "powered by distributed press" snippet then it should be good to merge.

Yep, it's updated https://github.com/hyphacoop/staticpub.distributed.press/pull/1/commits/4b85e21258f4193edf0216cc1a7c48591396e12d

2024-12-04 15:29 UTC, merged